apiVersion: v1
kind: Namespace
metadata:
  name: shop-system
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: order
  namespace: shop-system
spec:
  selector:
    matchLabels:
      app: order
  template:
    metadata:
      labels:
        app: order
    spec:
      terminationGracePeriodSeconds: 60
      containers:
        - name: order
          image: order-image